method: conv_onet
data:
  input_type: pointcloud
  pointcloud_noise: 0.005
  point_num: 8192
  grid_size: 32
  data_dir: groundtruth/gt_UNDC
  sample_dir: samples
  input_points_only: false

model:
  c_dim: 32
  encoder: local_pool_pointnet
  encoder_kwargs:
    hidden_dim: 32
    plane_type: 'grid'
    grid_resolution: 32
    unet3d: True
    unet3d_kwargs:
      num_levels: 3
      f_maps: 32
      in_channels: 32
      out_channels: 128
  decoder: local_decoder_Larger
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32

  checkpoint_dir: weights
training:
  bool: true
  float: false
  # out_dir: out/pointcloud/shapenet_grid32
  batch_size: 16 # 32->1
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 50
  visualize_every: 10000
  validate_every: 10000 # 10000->200
  checkpoint_every: 1000 # 2000->200
  backup_every: 10000
  n_workers: 16 # 8->1
  n_workers_val: 8 # 4->1
  epochs: 1000
  lr: 0.001
  lr_half_life: 10
test:
  bool: false
  float: false
  batch_size: 1
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: weights_pointcloud_bool.pth
  input: null
  postprocessing: true
generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
