inherit_from: configs/pointcloud/room_grid64.yaml

data:
  classes: ['']
  path: data/demo/synthetic_room_dataset
  pointcloud_n: 10000
  pointcloud_file: pointcloud
  pointcloud_noise: 0.0 # in test, we don't need noise
  voxels_file: null
  points_file: null
  points_iou_file: null

generation:
  generation_dir: generation_pretrained
  generate_pointcloud: false
  checkpoint_dir: models
  copy_input: false

test:
  # model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/models/pointcloud/room_grid64.pt
  model_file: pointcloud/room_grid64.pt
